version: '3'
services:
  api:
    build: ./api-gateway
    ports:
      - "3006:3006"
    links:
      - "auth"
      - "location"
    depends_on:
      - "auth"
      - "location"
    environment:
      - APP_HOST:"127.0.0.1"
      - LOCATION_SERVICE_HOST="location"
      - AUTH_SERVICE_HOST="auth"
  auth: 
    build: ./auth-service
    ports:
      - "3005:3005"
    links:
      - "mongodb"
    depends_on:
      - "mongodb"
    environment:
      - DB_HOST:"mongodb"
      - APP_HOST:"127.0.0.1"
  location:
    build: ./location-service
    ports:
      - "3004:3004"
    links:
      - "mongodb"
    depends_on:
      - "mongodb"
    environment:
      - DB_HOST:"mongodb"
      - APP_HOST:"127.0.0.1"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"