version: '3'

networks:
  emil-network:

services:
  api:
    build: ./api-gateway
    ports:
      - 3006:3006
    links:
      - auth
      - location
    depends_on:
      - auth
      - location
    environment:
      - LOCATION_SERVICE_HOST=location
      - AUTH_SERVICE_HOST=auth
    networks:
      - emil-network
  auth: 
    build: ./auth-service
    ports:
      - 3005:3005
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    networks:
      - emil-network
  location:
    build: ./location-service
    ports:
      - 3004:3004
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - DB_HOST=mongodb
    networks:
      - emil-network
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - emil-network
    volumes:
      - ./data:/data/db
