name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Location service - Install Dependencies
      working-directory: ./location-service
      run: npm install
    - name: Location service - Run Tests
      working-directory: ./location-service
      run: npm test
    - name: Location service - Build
      working-directory: ./location-service
      run: npm run build